---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: default
spec:
  encryptedData:
    password: AgAa89nMHs4zsgLmOft8K5N9uPkZaxvW+xPHn8ALIonPSM5JJWfjlMo6xD59/xi2F2Amdf23fdBkLlwMdM6RoDYV/bPucihM8MopQvNfecdzBtQZJw0U2h/4sV9osOGQLCoxvWKf+qfBqveiqQiVoscEKU60qUwWBqUOpc71I5FCv4MaIa10PyJ40HfujefzoKNO65QZVWgZpr4THp1q65I86HDc2jaFKdrczuqIe+Cg7xUdpk3/pr14NGf6LQjSm+VMnyOb5yMFKXoem6d+G3ys6VaU7ZWyhcK+mbvWXBIv1z44VwQLIAa0KaqRgzRWSdITb20jYMj3iNzt8mz40eAyepB8qzSaGQVVfwKCAgLL8h+Z7XDoNu2WAHiJtlSdW/N2Q5xQGjN/CaTiCIwFtRvqUTmZHSSfy54/r4OoJEPB62a687IvhWHiI8CPLnw9FwXmdSSPyu+mgJmjlTT3c6JWvGWz54pcj+TgTfAraDvsmNgg/F17vcpUgGHvTf88h/Iav09YwA0iOrRpuKZojGFL5dmRlgxxvmkSAiGkOUy4bGeIXS89RXeSx1whryGqVFvRradIYkMl7KQ3u+oQWuVZVVVWSLWA6KDQtnmGAGsyNZl0uMzl5C13LQ/ET/2KrUMr7+n/Cu/cWKYQmu394/P+N3quKYSCo4RrUFiG75WbdMex0HtBWRcbqVS8N26Sly3iGrf0Thb46A==
    username: AgBjqQk0sQYMONag4Ag/mYAqpRVNA0la9IFu1Z9k1ZqqQDXzLpy6K9MO4tTR5IownCa3OgFpLuWqW8hq5SpHA3OB+6/pn460BJUk5jgVPdE4IvcQxyXojd8UXJPftR9rcJ/q6ogOQCRSH2WKWB+eV9iX2LOL1GB0tGH0bxNOalZVJH+qTcbeSqHXIf/+ew1gKxcxZ9E/IkyCPcnA6c1SI7WSOXFu9H1S/VAt2kvFp5f5sox76qrsNQWyf7DqCjwuPcsN8lkaIOBuSVoQ1Dz1HSyqjjduTKnu4v3g7IVrQhqWbujX4LgbKUxvdVnjsXugedP+FqZtg3qO7wZ7fVL8uh1RgttUipZIjnW/DM7xSo/uQE6bGN7YlpIH2g6mGPuc5ye+0V3VEs/VGIsAbQc6UdywnfDRC0kj2mv5RRWpMIFuXTMDLC6NDnYIC54I97Kf3JCJ8JBHzo7TQlJ9vX0E0g+SGqC0j5Z5f7mw0n+/X4nnxgNYrcJL9tVz25qFpPqbqm4FtRghPa98hSTLho3XTOXQzFcGod3PMgdr6YIWHHEIfetuKIHxSvkPiB/nRa+BnzGveYuR/vaZtSL3O6zM2MOvBmUiDvTe5299I3MR+ZKrgYLP6bUJzYKialo+uCtmXPFSEnPuczfblLvGBmypC/NNKJunMHysj7x+qcipTeDGxlCPqDSrigjyBD2yfWMI1lfqHcJHCg==
  template:
    metadata:
      name: app-secret
      namespace: default
    type: Opaque
